import axios from "axios";
import path from "path";
import fs from "fs";

export async function GET() {
  try {
    const filePath1 = path.join(
      process.cwd(),
      "src/app/api/all-words/pool.json"
    );
    const filePath2 = path.join(
      process.cwd(),
      "src/app/api/all-words/allWords.json"
    );
    const fileContents1 = fs.readFileSync(filePath1, "utf8");
    const fileContents2 = fs.readFileSync(filePath2, "utf8");
    const data1 = JSON.parse(fileContents1);
    const data2 = JSON.parse(fileContents2);
    return Response.json({ pool: data1, allWords: data2 });
  } catch (err: unknown) {
    if (axios.isAxiosError(err)) {
      console.error("[PROCESS ERROR]", err.response?.data || err.message);
      return Response.json(
        { success: false, error: err.response?.data || err.message },
        { status: 500 }
      );
    }
    return Response.json({ success: false, error: err }, { status: 500 });
  }
}
const a = [
  "hacer",
  "primer",
  "poder",
  "mujer",
  "tener",
  "haber",
  "usted",
  "*carlos",
  "*maria",
  "igual",
  "saber",
  "*julio",
  "mundial",
  "*garcia",
  "*miguel",
  "*pedro",
  "conocer",
  "oficial",
  "poner",
  "volver",
  "fiscal",
  "*lopez",
  "*jorge",
  "lider",
  "*perez",
  "*alberto",
  "obtener",
  "tercer",
  "gestion",
  "*javier",
  "moral",
  "*sanchez",
  "perder",
  "*ramon",
  "*gomez",
  "comer",
  "parecer",
  "*castro",
  "canal",
  "*andres",
  "laboral",
  "sexual",
  "musical",
  "creer",
  "inicial",
  "alcance",
  "penal",
  "cancer",
  "estatal",
  "*victor",
  "*torres",
  "placer",
  "pared",
  "liberal",
  "ofrecer",
  "anual",
  "correr",
  "notable",
  "querer",
  "avance",
  "vender",
  "radical",
  "romero",
  "*elena",
  "vital",
  "rival",
  "cadaver",
  "atender",
  "rural",
  "cristal",
  "romper",
  "deber",
  "beber",
  "acceder",
  "taller",
  "balance",
  "*ramirez",
  "suponer",
  "recoger",
  "ejercer",
  "*vazquez",
  "digital",
  "parcial",
  "ramos",
  "*laura",
  "estable",
  "crecer",
  "imponer",
  "*sofia",
  "teatral",
  "ilegal",
  "vencer",
  "metal",
  "nacer",
  "vidal",
  "detener",
  "vegetal",
  "cable",
  "umbral",
  "traer",
  "*peter",
  "lateral",
  "merced",
  "meter",
  "suceder",
  "amable",
  "*maria",
  "mover",
  "verbal",
  "*samper",
  "mortal",
  "*reuter",
  "*walter",
  "*hitler",
  "poseer",
  "fatal",
  "naval",
  "natal",
  "portal",
  "coger",
  "ceder",
  "coral",
  "pascual",
  "litoral",
  "exponer",
  "brutal",
  "mineral",
  "escoger",
  "cometer",
  "*river",
  "lineal",
  "hable",
  "filial",
  "*ferrer",
  "atraer",
  "mensual",
  "*carter",
  "extraer",
  "*xavier",
  "potable",
  "genial",
  "trance",
  "corral",
  "*bernal",
  "crucial",
  "caudal",
  "*esther",
  "*racing",
  "frontal",
  "padecer",
  "gradual",
  "prever",
  "vocal",
  "plural",
  "temer",
  "cocer",
  "hable",
  "semanal",
  "*france",
  "viable",
  "comence",
  "chofer",
  "*roger",
  "jupiter",
  "someter",
  "puntual",
  "soler",
  "arsenal",
  "funeral",
  "romance",
  "cesped",
  "espiral",
  "recital",
  "cordial",
  "joder",
  "retener",
  "*inter",
  "usual",
  "*anibal",
  "dorsal",
  "marcial",
  "*miller",
  "cabal",
  "valer",
  "postal",
  "renal",
  "super",
  "*royal",
  "*center",
  "vence",
  "*mahler",
  "causal",
  "*journal",
  "*nadal",
  "chofer",
  "fetal",
  "*weber",
  "anormal",
  "huesped",
  "sensual",
  "declive",
  "*victor",
  "remover",
  "*mistral",
  "nominal",
  "viral",
  "irreal",
  "neutral",
  "foral",
  "*willy",
  "racial",
  "*oliver",
  "*wagner",
  "*united",
  "comunal",
  "mural",
  "*mohamed",
  "radial",
  "llover",
  "inusual",
  "*boyer",
  "*mister",
  "proveer",
  "*alfred",
  "laser",
  "carecer",
  "lance",
  "carnal",
  "chaval",
  "*kelly",
  "*turner",
  "ranking",
  "tender",
  "acoger",
  "austral",
  "*holding",
  "literal",
  "floral",
  "bienal",
  "nasal",
  "genital",
  "*billy",
  "*ramon",
  "*manager",
  "coser",
  "*steiner",
  "*walker",
  "colosal",
  "doquier",
  "*spencer",
  "textual",
  "*premier",
  "*pascal",
  "*baker",
  "super",
  "gremial",
  "master",
  "*xabier",
  "trivial",
  "vaginal",
  "cajal",
  "desleal",
  "chance",
  "*ester",
  "*pasqual",
  "letal",
  "*nelly",
  "fiable",
  "*boeing",
  "banal",
  "matinal",
  "feudal",
  "*garcia",
  "merecer",
];
export async function POST() {
  try {
    const filePath1 = path.join(
      process.cwd(),
      "src/app/api/all-words/pool.json"
    );

    const fileContents1 = fs.readFileSync(filePath1, "utf8");
    const data1: string[] = JSON.parse(fileContents1);
    const marcadas: string[] = data1.filter((w) => w.includes("*"));
    console.log(marcadas.length, marcadas[1]);

    const aux = a
      .filter((w) => w.includes("*"))
      .map((p) => (p.startsWith("*") ? p.slice(1) : p));

    console.log(aux[1], aux[2], "11");

    const resultado = data1.filter((palabra) => !aux.includes(palabra));
    const outputPath = path.join(
      process.cwd(),
      "src/app/api/all-words/pool2.json"
    );
    const jsonOutput = JSON.stringify(resultado, null, 2); // bonito con indentación
    fs.writeFileSync(outputPath, jsonOutput, "utf-8");
    return Response.json(marcadas);
  } catch (error) {
    console.log(error);
    return Response.json("{}");
  }
}
